### PR TITLE
fix: make priority calculations consistent for TestTxMempool_ReapMaxBytes

### LINKED ISSUE #1132: `TestTxMempool_ReapMaxBytesMaxGas` flake
## Problem

```
--- FAIL: TestTxMempool_ReapMaxBytesMaxGas (0.02s)
    mempool_test.go:332: 
        	Error Trace:	/home/runner/work/celestia-core/celestia-core/mempool/v1/mempool_test.go:332
        	            				/home/runner/work/celestia-core/celestia-core/mempool/v1/mempool_test.go:344
        	Error:      	Not equal: 
        	            	expected: []int64{9984, 9744, 9679, 9669, 9650, 9594, 9530, 9445, 9345, 9330, 9273, 8774, 8756, 8681, 8661, 8651, 8641}
        	            	actual  : []int64{9984, 9744, 9679, 9669, 9650, 9594, 9530, 9445, 9345, 9330, 9273, 8774, 8756, 8681, 8661, 8651, 8136}
        	            	
        	            	Diff:
        	            	--- Expected
        	            	+++ Actual
        	            	@@ -17,3 +17,3 @@
        	            	  (int64) 8651,
        	            	- (int64) 8641
        	            	+ (int64) 8[136](https://github.com/celestiaorg/celestia-core/actions/runs/6694512516/job/18259850106#step:6:137)
        	            	 }
        	Test:       	TestTxMempool_ReapMaxBytesMaxGas
FAIL
```

## Occurences

1. https://github.com/celestiaorg/celestia-core/actions/runs/6694512516/job/18259850106#step:6:123

### PR DESCRIPTION
**Pull request by evan-forbes**
## Description

This test is currently hyper flakey because it doesn't calculate priorities consistently due to the txs being different sizes.

closes #1132

### CODE REVIEW

File: mempool/v1/mempool_test.go [hunk 1]
```diff
@@ -306,11 +306,11 @@ func TestTxMempool_Flush(t *testing.T) {
 }
 
 func TestTxMempool_ReapMaxBytesMaxGas(t *testing.T) {
+	totalSizeBytes := int64(5800)
```
Comment (staheri14) [inline mempool/v1/mempool_test.go:309]: [Question] Where does the 5800 value come from? would be good to add a comment in the code

**Review by staheri14 — APPROVED** [review]

File: mempool/v1/mempool_test.go (hunk 1 above)
Comment (evan-forbes) [reply mempool/v1/mempool_test.go:313]: yeah true, 

While its something we might want to know in the future, the exact overhead introduced by the mempool and encoding isn't specified already and would take a while to calculate accurately.

The txs being used are 38 bytes (and thanks to this fix they are actually consistent), and there should be 100 of them. Presumably the rest is encoding overhead.

Comment (evan-forbes) [reply mempool/v1/mempool_test.go:313]: added docs here tho https://github.com/celestiaorg/celestia-core/pull/1170/commits/dbbd7eeed803cc9d2af1d11524b76fafb29c1f32

**Review by staheri14 — DISMISSED** [review]
LGTM!

**Review by rootulp — DISMISSED** [review]

**Comment by evan-forbes** [comment]
realized that we have duplicate tests in cat, so I fixed those as well.

**Review by rootulp — APPROVED** [review]

**Review by staheri14 — APPROVED** [review]
