### PR TITLE
fix: pass version when converting between proto consensus params types

### LINKED ISSUE #1201: The version isn't passed to to the app during `InitChain` for v0.34.x
on v0.34.x-celestia, but not main I don't think, the version is filtered when converting types

https://github.com/celestiaorg/celestia-core/blob/5a5e689942a700bb08d369b1821e28443b829619/types/protobuf.go#L100-L109

This causes `InitChain` to not pass the version, which causes the app to not store the param. Fortunately, this should only have an effect on new networks since existing networks are not on v2, and the version will be set after the upgrade.

### PR DESCRIPTION
**Pull request by evan-forbes**
## Description

closes #1201 this issue only affects v0.34.x

### CODE REVIEW

**Review by ninabarbakadze — APPROVED** [review]

File: types/protobuf.go [hunk 1]
```diff
@@ -105,6 +105,7 @@ func (tm2pb) ConsensusParams(params *cmtproto.ConsensusParams) *abci.ConsensusPa
 		},
 		Evidence:  &params.Evidence,
 		Validator: &params.Validator,
+		Version:   &params.Version,
```
Comment (rootulp) [inline types/protobuf.go:108]: I have a few non-blocking questions.
1. Is this function a translation layer from CometBFT protobuf types to ABCI protobuf types? Silly question but why does it need to exist? The types seem _almost_ interchangeable.
1. Was this broken upstream or a Celestia specific modification in celestia-core caused this issue? It looks like upstream is broken too: https://github.com/cometbft/cometbft/blob/e0e50aa9fca730ec208b67b54e48c8bdc630c17b/types/protobuf.go#L100-L109
1. Should we add a unit test in protobuf_test.go to prevent regressions?

**Review by staheri14 — APPROVED** [review]

**Review by rootulp — APPROVED** [review]

File: types/protobuf.go (hunk 1 above)
Comment (evan-forbes) [reply types/protobuf.go:108]: this isn't broken on main, where we just use the toProto method. here I wanted to minimize the number the changes, but the best approach would be to do what main does, which is to delete these and only use the ToProto methods and have round trip unit tests
